---
title: "Credit Model"
output: html_notebook
---

```{r setup}
# Packages ----
library(tidymodels)
library(tidyverse)
library(DBI)
library(pins)
library(ranger)
```

Collect data from database to build model.
```{r data}
con <- dbConnect(RSQLite::SQLite(), "data/credit")
credit_data <- tbl(con, "credit") %>% 
  collect() %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(job = as.factor(job))
dbDisconnect(con)

credit_data
```

Build random forest model using the `ranger` package
```{r}
rf_mod <- rand_forest(mode = "classification") %>% 
  set_engine("ranger")

rf_fit <- rf_mod %>% 
  fit(risk ~ ., data = credit_data)

rf_fit
```

Save the trained model to a pin on RStudio Connect
```{r}
board_register_rsconnect(server = "https://colorado.rstudio.com/rsc",
                         key = Sys.getenv("connect_key"))
model_details <- list(
  model = rf_fit,
  train_date = lubridate::today(),
  age = c(min(credit_data$age), median(credit_data$age), max(credit_data$age)),
  sex = sort(unique(credit_data$sex)),
  jobs = sort(unique(credit_data$job)),
  housing = sort(unique(credit_data$housing)),
  saving_accounts = sort(unique(credit_data$saving_accounts)),
  checking_account = sort(unique(credit_data$checking_account)),
  duration = c(min(credit_data$duration), median(credit_data$duration), max(credit_data$duration)),
  purpose = sort(unique(credit_data$purpose))
)

pin(x = model_details,
    name = "credit_risk_model",
    description = "Credit Risk Model trained on Kaggle dataset",
    board = "rsconnect")
```

